version: '3'

services:
  my_python:
    image: local/my_python:pytorch
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    restart: always

    # for GPU
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    # GUI for WSLg
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
