# Web API からサジェスト
# see https://keypirinha.com/packages/websuggest.html

[main]
default_action = browse
enable_predefined_providers = yes
enable_predefined_items = no

#------------#
# Predefined #
#------------#

[item/Google]
provider = google

[item/Wikipedia]
provider = wikipedia

[item/Youtube]
provider = youtube

[item/Amazon]
provider = amazon
