session_name: dev
shell_command_before:
  - 'eval "$(mise activate zsh)"'
start_directory: "${PWD}"
windows:
  - window_name: code
    layout: main-vertical
    options:
      main-pane-width: 120
    panes:
      - shell_command:
          - nvim
      - zsh

  - window_name: terminal
    panes:
      - zsh

  - window_name: git
    panes:
      - shell_command:
          - lazygit
