# bind the prefix
set -g prefix C-o

# top status bar
# set-option -g status-position top

# set true color (24-bit color)
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# Tmux Plugin Manager 'tpm'
set -g @plugin 'tmux-plugins/tpm'

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run-shell '~/.tmux/plugins/tpm/tpm'
