# see below for documentation
# https://mise.jdx.dev/configuration.html

[tools]
# for homesick
ruby = "2.7.8"
# for bug
fzf = "0.53.0"
ghq = "latest"
bat = "latest"
eza = "latest"
ripgrep = "latest"

[settings]
# for Tkinter (prebuild binaries doesn't contain GUI modules)
# see https://www.python.jp/install/ubuntu/index.html
python_compile = true
# for task runner
experimental = true

# # see https://mise.jdx.dev/environments.html
# [env]
# _.path = ["/usr/local/cuda-11.8/bin"]
# # see https://keats.github.io/tera/docs/#default
# LD_LIBRARY_PATH = "/usr/local/cuda-11.8/lib64:{{env.LD_LIBRARY_PATH | default(value='')}}"
