# see below for documentation
# https://mise.jdx.dev/configuration.html

[tools]
# for homesick
ruby = "2.7.8"
# for bug
fzf = "0.53.0"
ghq = "latest"
bat = "latest"
eza = "latest"
ripgrep = "latest"

[settings]
# for Tkinter (prebuild binaries doesn't contain GUI modules)
# see https://www.python.jp/install/ubuntu/index.html
python_compile = true

# # see https://mise.jdx.dev/environments.html
# [env]
# _.path = [
#     # adds an absolute path
#     "~/.local/share/bin",
#     # adds a path relative to the .mise.toml, not PWD
#     "./node_modules/.bin",
# ]
# LD_LIBRARY_PATH = "/some/path:{{env.LD_LIBRARY_PATH}}"
