[tools]
# for homesick
ruby = "2.7.8"
fzf = "0.53.0"
ghq = "latest"
bat = "latest"
eza = "latest"
ripgrep = "latest"

[settings]
# see https://www.python.jp/install/ubuntu/index.html
python_compile = true
