version: '3'

services:
  clion:
    image: local/clion:ubuntu20.04-ssh
    build:
      context: .
      dockerfile: ./clion-ssh.dockerfile
    restart: always

    #######
    # SSH #
    #######
    ports:
     - "50023:2222"

    #######
    # GUI #
    #######
    # network_mode: "host"
    # environment:
    #   - DISPLAY
    # volumes:
    #   # - type: bind
    #   #   source: $HOME/.Xauthority
    #   #   target: /root/.Xauthority
    #   - type: bind
    #     source: /tmp/.X11-unix
    #     target: /tmp/.X11-unix
