version: '3'

services:
  clion:
    image: local/clion:test
    build:
      context: .
      dockerfile: ./clion.dockerfile

    #######
    # SSH #
    #######
    ports:
     - "127.0.0.1:50023:2222"

    #######
    # GUI #
    #######
    # network_mode: "host"
    environment:
      - DISPLAY
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw"
      - $HOME/.Xauthority:/root/.Xauthority:rw
    
