snippets:
  - name: "[null] null"
    keyword: "null,"
    snippet: ">/dev/null 2>&1"
    # auto expand condition
    # If not defined, it is only valid at the beginning of a line.
    context:
      # buffer: ''
      lbuffer: '.+\s'
      # rbuffer: ''

  - name: "[b] branch"
    keyword: "b,"
    snippet: git symbolic-ref --short HEAD
    context:
      lbuffer: '^git\s+checkout\s+'
    evaluate: true # eval snippet

  - name: "[kgen] ssh keygen"
    keyword: "kgen,"
    snippet: "ssh-keygen -t ed25519 -P \"\""

  - name: "[pgen] generate password"
    keyword: "pgen,"
    snippet: "openssl rand -base64 12"
  
  - name: "[relogin] relogin shell"
    keyword: "relogin,"
    snippet: "exec $SHELL -l"

  - name: "[sha2] sha2 hash"
    keyword: "sha2,"
    snippet: "openssl passwd -6 -salt 'SALTsalt'"
  
  - name: "[find] search by name"
    keyword: "find,"
    snippet: "find . -type f -name '*{{.query}}*'"

  - name: "[grep] search by content"
    keyword: "grep,"
    snippet: "grep '{{.query}}' -rl ."

completions:
  # simple sourceCommand, no callback
  - name: kill signal
    patterns:
      - "^kill -s $"
    sourceCommand: "kill -l | tr ' ' '\\n'"
    options:
      --prompt: "'Kill Signal> '"

  # use excludePatterns and callback
  - name: kill pid
    patterns:
      - "^kill( .*)? $"
    excludePatterns:
      # -l, -n or -s is followed by SIGNAL instead of PID
      - " -[lns] $"
    sourceCommand: "LANG=C ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"
  
  - name: ssh hosts
    patterns:
      - "^ssh( .*)? $"
    sourceCommand: "cat ~/.ssh/config | grep '^Host ' | awk '{print $2}'"
    options:
      --prompt: "'SSH Host> '"

  # # Use null (\0) termination Input / Output
  # - name: chdir
  #   patterns:
  #     - "^cd $"
  #   sourceCommand: "find . -path '*/.git' -prune -o -maxdepth 5 -type d -print0"
  #   options:
  #     # Added --read0 if null termination is used in `sourceCommand` output.
  #     --read0: true
  #     --prompt: "'Chdir> '"
  #     --preview: "cd {} && ls -a | sed '/^[.]*$/d'"
  #   callback: "cut -z -c 3-"
  #   callbackZero: true # null termination is used in `callback` I/O