version: '3'

services:
  my_python:
    image: local/my_python:miniforge3
    build:
      context: .
      dockerfile: ./Dockerfile
    # needed for miniforge images
    tty: true
    restart: always


    # for GPU
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    #######
    # GUI #
    #######
    # network_mode: "host"
    # environment:
    #   - DISPLAY
    # volumes:
    #   # - type: bind
    #   #   source: $HOME/.Xauthority
    #   #   target: /root/.Xauthority
    #   - type: bind
    #     source: /tmp/.X11-unix
    #     target: /tmp/.X11-unix
