version: '3'

services:
  pycharm:
    image: local/pycharm:ssh
    build:
      context: .
      dockerfile: ./pycharm.dockerfile
    restart: always

    # for GPU
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    # SSH
    ports:
     - "50024:2222"

    #######
    # GUI #
    #######
    # network_mode: "host"
    # environment:
    #   - DISPLAY
    # volumes:
    #   # - type: bind
    #   #   source: $HOME/.Xauthority
    #   #   target: /root/.Xauthority
    #   - type: bind
    #     source: /tmp/.X11-unix
    #     target: /tmp/.X11-unix
